### ISSUE TITLE
website check (ispconfig 3.1.15p2): Internal Server Error  Undefined array key "server_php_id"

### ISSUE THREAD

**Issue by kskarlatos** [olaulau/IspAdmin#6]
on a old phpconfig 3.1.15p2 i get when running website check:
2025/02/14 08:33:04 [error] 18075#18075: *675298 FastCGI sent in stderr: "PHP message: Undefined array key "server_php_id"; PHP message: [php/model/PhpInfos.php:58] ; PHP message: [php/model/PhpInfos.php:58] Base->{closure}(); PHP message: [php/controller/FrontCtrl.php:325] model\PhpInfos->extractInfos(); PHP message: [index.php:15] Base->run()" while reading response header from upstream, client: 85.75.179.235, server: ----, request: "GET /websites/check HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php7.3-fpm/web250.sock:",

**Comment by olaulau** [comment]
On my servers, I don't use website without PHP, it makes things crash quite often.
Can you try latest commit https://github.com/olaulau/IspAdmin/commit/c32d07f9135ce68558505ab84482161a67d83799, which should fix this ?

BTW,  you should :
- update your OS and ISPConfig regularly
- anonymize your issues (client IP, server hostname ...)

**Comment by kskarlatos** [comment]
Unfortunately the fix didn't work.
I still get 2025/02/17 11:27:52 [error] 10079#10079: *2063859 FastCGI sent in stderr: "PHP message: Undefined array key "server_php_id"; PHP message: [php/model/PhpInfos.php:58] ; PHP message: [php/model/PhpInfos.php:58] Base->{closure}(); PHP message: [php/controller/FrontCtrl.php:329] model\PhpInfos->extractInfos(); PHP message: [index.php:15] Base->run()" while reading response header from upstream, client: 85.75.179.235, server: ---, request: "GET /websites/check HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php7.3-fpm/web250.sock:", host: "---", referrer: "---/websites/list"

If this isnt easy to fix then i think its better to let this issue go, as this is an old server and i will migrate from it anyway. 
PS. I forgot about anonymizing, thanks!

**Comment by olaulau** [comment]
can you try commit https://github.com/olaulau/IspAdmin/commit/a877496ed05a1e751135e531f430075af79f7f4b please ?

**Comment by kskarlatos** [comment]
it works perfectly now, thanks!
